[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sf/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://www.youtube.com/watch?v=tPe71sSEj-g"
  status = 301
  force = true